// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0GWBMBlJzTMj6JuPsUjY7FOnJ9MOrx7I',
    appId: '1:269969359176:web:2890d5d5cb128e9165f37d',
    messagingSenderId: '269969359176',
    projectId: 'sngce3-689c8',
    authDomain: 'sngce3-689c8.firebaseapp.com',
    storageBucket: 'sngce3-689c8.appspot.com',
    measurementId: 'G-VCPH8P7LWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7qP3wTq9zSH3XkA44XBe30H6h1eNuV40',
    appId: '1:269969359176:android:b14d55ad917081d265f37d',
    messagingSenderId: '269969359176',
    projectId: 'sngce3-689c8',
    storageBucket: 'sngce3-689c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0OjDohHOBGwjsptWux7G08CzxmQcAq0Q',
    appId: '1:269969359176:ios:3f3c8c5117f5c88465f37d',
    messagingSenderId: '269969359176',
    projectId: 'sngce3-689c8',
    storageBucket: 'sngce3-689c8.appspot.com',
    iosBundleId: 'com.example.controler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0OjDohHOBGwjsptWux7G08CzxmQcAq0Q',
    appId: '1:269969359176:ios:3f3c8c5117f5c88465f37d',
    messagingSenderId: '269969359176',
    projectId: 'sngce3-689c8',
    storageBucket: 'sngce3-689c8.appspot.com',
    iosBundleId: 'com.example.controler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0GWBMBlJzTMj6JuPsUjY7FOnJ9MOrx7I',
    appId: '1:269969359176:web:0f073a760f0d648465f37d',
    messagingSenderId: '269969359176',
    projectId: 'sngce3-689c8',
    authDomain: 'sngce3-689c8.firebaseapp.com',
    storageBucket: 'sngce3-689c8.appspot.com',
    measurementId: 'G-WWL4K5V22H',
  );

}